name: docker-build-latest

env:
  dockerhub_repository: "darkpixel/kutt"
  dockerhub_tag: "develop"
  IMAGE_NAME: kutt

on:
  push:
    branches:
      - develop
jobs:
  dockerhub-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg commit="$GITHUB_SHA"

      - name: Sign in to GHCR
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          [ "$VERSION" == "develop" ] && VERSION=develop
          echo "::notice IMAGE_ID=$IMAGE_ID"
          echo "::notice VERSION=$VERSION"
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
